In [1]:
import torch
import numpy

In [4]:
# S, W, B
S = torch.tensor( [0.4017857, 0.59821427] )
W = torch.tensor( [[0.23852903, 0.7614557],[0.73281455, 0.26717022]] )
B = torch.tensor( [[0.53253984, 0.46744487], [0.40410468, 0.5958801]])

In [47]:
#Wt * S = R:
R = W.T @ S
R = R / R.sum()
R

tensor([0.5342, 0.4658])

In [48]:
# Wr
Wr = torch.zeros_like(W)
Wr[ W > 0.2 ] = 1
Wr

tensor([[1., 1.],
        [1., 1.]])

In [49]:
# Wr * S = T
T = Wr.T @ S
T

tensor([1., 1.])

In [51]:
# C = sig( rho * ( T - kappa ))
rho = 10
kappa = 0.5
C = torch.sigmoid( rho * (  T - kappa ) )
C

tensor([0.9933, 0.9933])

In [52]:
# I = R * C
I = R * C
I = I / I.sum()
I

tensor([0.5342, 0.4658])

In [53]:
BB = B - torch.diag( B.diag() )
BB = BB.T / torch.sum( BB, 1 )
D = BB @ I
D

tensor([0.4658, 0.5342])

In [54]:
# Bn = aB + (1-a)W
alpha = 0.90
Bn = alpha * B + (1 - alpha) * W
Bn

tensor([[0.5031, 0.4968],
        [0.4370, 0.5630]])

In [55]:
# E = (I + D) * 1_000_000_000
E = (I + D) * 1_000_000_000 / 2
E

tensor([5.0000e+08, 5.0000e+08])

In [57]:
E.sum()

tensor(1.0000e+09)